server/db/models/index.js
server/db/models/order.js

We did the Order model , imported it to the index.js

added Order Model

---

server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

Products model

---

server/api/index.js
server/api/products.js
server/db/models/cart.js
server/db/models/index.js

Defined Cart model with Quantity column

Cart model branch

---

server/api/index.js
server/api/products.js

Products routes added , include for admin needs:
GET Products
GET single product
Admin POST new product
Admin PUT update product
Admin DELETE product
Admin's routes protected with middleware

added products routes

---

script/seed.js
server/db/models/cart.js
server/db/models/index.js
server/db/models/order.js

Orders seed data

---

client/app.js
client/components/AllProducts.js
client/components/SingleProductCard.js
client/store/index.js
client/store/product.js

Added AllProducts Component and SingleProductCard Component (for allProducts view)

added AllProducts and SingleCard components

---

server/api/index.js
server/api/users.js

User routes

---

client/components/SingleProductCard.js

new routes for all products view

merged for second day

---

client/routes.js

Added AllProducts component routes missing from master

two new routes for products

---

client/components/AllUsers.js
client/routes.js
client/store/index.js
client/store/users.js
script/seed.js

New component for admins only added
This AllUsers component lists all users in the db.
Only admins can navigate to this component

all users component added

---

client/store/cart.js

Cart reducer

---

client/routes.js
package-lock.json
script/seed.js
server/api/products.js
server/api/users.js
server/db/models/cart.js
server/db/models/order.js
server/db/models/product.js

added comments

---

client/store/cart.js
server/api/users.js

changes to cart reducer and user routes

---

client/components/Cart.js
server/api/users.js

Updated to get route in users to get all of the current cart items
Updated the Cart component to retrieve the users cart from the state

Cart routes

---

client/components/Cart.js
server/api/users.js

Cart component has been updated to handle empty carts
User route to retrieve cart content has been updated to handle empty cart logic

Added empty cart logic to the Cart component and get cart route

---

server/api/users.js

Added functionality to add to cart route that increments quantity

Cart thunk user routes

---

client/components/Checkout.js
client/components/OrderConfirmation.js
client/routes.js
client/store/cart.js
public/style.css
server/api/products.js
server/api/users.js

- created checkout component
- display order summary, shipping form, payment section 
- "place order" button functionality
- Note: in progress, magic method to create new empty Order after user places current order

Checkout component

---

client/components/Cart.js
client/components/Checkout.js
client/components/SingleProductCard.js
client/components/navbar.js
client/routes.js
client/store/cart.js
public/index.html
public/style.css
script/seed.js
server/api/users.js

- Moved Order.update request from Axios request to api route  in routes/users.js
- Created magic method to create new empty order with userId
- Renamed submit_cart action and thunk to checkout_cart for clarity
- Updated action to return initialState to clear cart, instead of empty products arry
- Added order total and quantity to checkout page

Checkout component updated

---

client/components/Cart.js
client/store/cart.js
server/api/index.js
server/api/quantity.js
server/api/users.js

Added increment and decrement functionality

Increment route

---

client/components/Cart.js
client/components/navbar.js

checkout button works and link to cart from navbar changed

checkout button works

---

client/components/Cart.js
client/store/cart.js
server/api/users.js

Made updates to the cart reducer, Cart component and user routes to enable removing items from the cart.

Remove item

---

client/components/Cart.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/store/guestCart.js

visitor cart works, can add, decrease, increase, checkout , remove

visitor cart works

---

client/components/Cart.js
client/components/Checkout.js
client/routes.js

Made updates to the Cart and Checkout Components so that the tots variable reflects the quantity
The checkout button wasn't navigating to the checkout page so I update the routes ever so slightly.

totals now reflect price AND quantity in the logged in user cart

---

client/components/Cart.js
client/store/cart.js
server/api/quantity.js

Increment and decrement fixed in cart. 
Cart items no longer shuffle
Cart items can't be reduced below 1

increase and decrease cart items without reshuffling

---

client/components/Cart.js
client/components/Checkout.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/navbar.js
client/store/cart.js
public/style.css

- navbar link css
- checkout form css in checkout components 
- minor update in text spacing to cart components

Navbar update

---

client/components/Checkout.js
client/components/GuestCheckout.js
public/style.css

GuestCheckout and Checkout Components:
- added form validation
- requires first name, last name, email, and address to be filled out
- checks if email address is valid email address 
Note: If we have time, may want to break out Form component into a separate component to pass into this component.

form validation

---

client/components/InStock.js
client/components/SingleProduct.js
client/routes.js
client/store/index.js
client/store/instock.js
script/seed.js
server/api/products.js
server/db/models/product.js

Category - in stock p1. of 2

---

client/components/GuestCart.js
client/components/OrderHistory.js
client/components/navbar.js
client/routes.js
client/store/cart.js
client/store/index.js
client/store/orderHistory.js
package-lock.json
package.json
public/style.css
script/seed.js
server/api/users.js
server/db/models/order-history.js

Order History component, 
Reducer,
Express Route for fetching of old orders,
Link from nav bar for users,
added Current price for dummy data in seed file

History of users orders

---

client/components/AllProducts.js
client/components/Pagination.js
public/style.css

Pagination component , added 3 pages, 4 products per page

pages for all products view

---

server/api/users.js

Cart debug. Users route for adding new product needed to be eager loading the order onto the product object

Cart debug

---

client/components/Cart.js
client/store/cart.js
server/api/users.js

User before login can add products to the cart,
after login still can see that items in cart,
cart products from previous session will be there too

Merging carts

---

client/components/Cart.js
client/components/Checkout.js
client/components/EditAccountForm.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/MyAccount.js
client/components/OrderHistory.js
client/components/navbar.js
client/routes.js
client/store/user.js
public/style.css
script/seed.js
server/api/users.js
server/db/models/user.js

- changed OrderHistory component to MyAccount
- added user account info to the component
- created account edit form component
- created thunk and action for updated user info
- CSS update: added underline to category links
**Note for the edit user form:** 
If a field is left blank on the edit form, the back-end will change it to a blank field. I will look into this more to figure out how to preserve fields that don't need an edit, but may not figure it out by the end of the day.

User profile

---

client/components/EditAccountForm.js

added pre-filled fields in componentDidMount
this should fix the bug where if a field is left blank, the back-end field is updated to blank!

minor update to user edit form

---

client/components/AllProducts.js
client/components/SingleColorProducts.js

3 changes: 
color of one item in seed.js
able to see category of one item
removed 'exact' in Link

able to see category og one item

---

package-lock.json
package.json
script/seed.js
server/index.js

- npm install helmet
- added helmet to express index.js file
- should protect our routes from common web vulnerabilities
https://expressjs.com/en/advanced/best-practice-security.html

added security middleware

---

.gitignore

took away slash

---

public/style.css

made the orders show up vertically instead of horizontally

updated order history styling

---

.gitignore
README.md

Read me update
